### ISSUE TITLE
Use case question, with efk

### ISSUE THREAD

**Issue by slimee** [floragunncom/search-guard-helm#10]
Hi, thanks you for this work.

I am new to search-guard.
Is it possible to secure my efk deployment with this chart?

Thanks you

**Comment by floragunncom** [comment]
You need to add the fluentd part (as daemonset i assume) but then i guess it should work

**Comment by slimee** [comment]
Ok,

Do you mean fluentbit will need to auth into ES after search-guard deployment?

**Comment by floragunncom** [comment]
Yes, either via basic authentication or client certificate or any other auth method Search Guard supports.

Will close this as it is not a bug.  Feel free to ask any question here: https://groups.google.com/forum/#!forum/search-guard
