### ISSUE TITLE
Automate Cert generation

### ISSUE THREAD

**Issue by ron1** [floragunncom/search-guard-helm#2]
The current Search Guard Helm Chart requires external certificate generation in order to achieve a production deployment. Since usage of self-signed certificates is so common with Kubernetes-based deployments, consider simplifying the deployment by moving cert generation to Helm as described in blog "Move Your Certs to Helm" https://medium.com/nuvo-group-tech/move-your-certs-to-helm-4f5f61338aca and as implemented in an representative chart such as https://github.com/kubedb/cli/blob/master/chart/kubedb/templates/apiregistration.yaml.

**Comment by floragunncom** [comment]
That is scheduled for beta2. Do you like to prepare a PR for that?

**Comment by floragunncom** [comment]
done, but implemented with our own tls tool
